---
_hotel_id: THE465
_portal_id: required-but-empty
_root_path: https://qa4.ttaws.com/rt
latitude: 40.73247
longitude: -73.99692
name: The Marlton Hotel
email: steffan@traveltripper.io
phone_number: "--"
address:
  street1: 5 W 8th St
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10011'
